include:
  - board: nice_nano_v2
    shield: eyeslash_corne_central_dongle,dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyeslash_corne_central_dongle_oled
  
  - board: nice_nano_v2
    shield: eyeslash_corne_peripheral_left,nice_view_adapter
    artifact-name: eyeslash_corne_peripheral_left
  
  - board: nice_nano_v2
    shield: eyeslash_corne_peripheral_right,nice_view_adapter
    artifact-name: eyeslash_corne_peripheral_right
  
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
